
import React, { useState, useEffect } from 'react';
import { generateExamPaper } from '../services/geminiService';

interface ExamsProps {
  onAskAI: (text: string) => void;
  onMistake: (question: any) => void;
  examLevel: string;
}

const Exams: React.FC<ExamsProps> = ({ onAskAI, onMistake, examLevel }) => {
  const [view, setView] = useState<'selection' | 'generating' | 'test'>('selection');
  const [isFocusMode, setIsFocusMode] = useState(false);
  const [timer, setTimer] = useState(1800); 
  const [examConfig, setConfig] = useState({
    examType: 'General Study',
    subject: '',
    chapters: '',
    difficulty: 'Medium',
    level: examLevel,
    language: 'English'
  });
  const [questions, setQuestions] = useState<any[]>([]);

  const levels = [
    'Primary (Class 1-5)',
    'Middle (Class 6-8)',
    'Secondary (Class 9-10)',
    'Sr. Secondary (Class 11-12)',
    'JEE / NEET / Competitive',
    'Graduation (BA/BSc/BCom)',
    'B.Tech / Medical / Law',
    'Post Graduation (MA/MSc)',
    'PhD / Research'
  ];

  const languages = ['English', 'Hindi', 'Bengali', 'Tamil', 'Telugu', 'Marathi', 'Gujarati', 'Kannada', 'Hinglish'];

  useEffect(() => {
    let interval: any;
    if (view === 'test') {
      interval = setInterval(() => {
        setTimer(prev => (prev > 0 ? prev - 1 : 0));
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [view]);

  useEffect(() => {
    if (!levels.includes(examLevel)) {
        setConfig(prev => ({...prev, level: levels.find(l => l.includes(examLevel)) || examLevel}));
    } else {
        setConfig(prev => ({...prev, level: examLevel}));
    }
  }, [examLevel]);

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  };

  const handleGenerate = async () => {
    if (!examConfig.subject) {
        alert("Please specify a subject (e.g., Mathematics, History, Quantum Physics)");
        return;
    }
    setView('generating');
    const q = await generateExamPaper(examConfig);
    setQuestions(q);
    setView('test');
    setTimer(1800);
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const content = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>BharatEdu - ${examConfig.subject} - ${examConfig.level}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap');
            body { font-family: 'Inter', sans-serif; padding: 50px; line-height: 1.6; color: #1a1a1a; }
            .header { text-align: center; border-bottom: 2px solid #eee; margin-bottom: 40px; padding-bottom: 20px; }
            .header h1 { margin: 0; font-size: 24px; color: #4f46e5; }
            .header p { margin: 5px 0; color: #666; font-size: 14px; font-weight: bold; }
            .metadata { display: flex; justify-content: space-between; margin-bottom: 30px; font-size: 12px; color: #444; background: #f8fafc; padding: 10px; border-radius: 8px; }
            .question { margin-bottom: 35px; page-break-inside: avoid; border-left: 3px solid #e2e8f0; padding-left: 20px; }
            .question-text { font-size: 16px; font-weight: bold; margin-bottom: 15px; display: block; }
            .options { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
            .option { font-size: 14px; color: #334155; }
            .footer { margin-top: 60px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #eee; pt: 20px; }
            @media print {
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>BHARATEDU - Universal Sadhana Hub</h1>
            <p>Practice Examination Paper</p>
          </div>
          <div class="metadata">
            <div><strong>Subject:</strong> ${examConfig.subject}</div>
            <div><strong>Level:</strong> ${examConfig.level}</div>
            <div><strong>Language:</strong> ${examConfig.language}</div>
            <div><strong>Difficulty:</strong> ${examConfig.difficulty}</div>
          </div>
          ${questions.map((q, i) => `
            <div class="question">
              <span class="question-text">Q${i + 1}. ${q.text}</span>
              <div class="options">
                ${q.options.map((opt: string, oi: number) => `
                  <div class="option">(${String.fromCharCode(65 + oi)}) ${opt}</div>
                `).join('')}
              </div>
            </div>
          `).join('')}
          <div class="footer">
            This document was automatically generated by Chanakya AI on BharatEdu. 
            Educational Use Only. © ${new Date().getFullYear()} BharatEdu.
          </div>
          <script>
            window.onload = () => {
              window.print();
              // window.close(); // Optional: close tab after print
            };
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(content);
    printWindow.document.close();
  };

  const trackMistake = (q: any) => {
    onMistake(q);
    onAskAI(q.text);
  };

  if (view === 'generating') {
    return (
      <div className="h-[80vh] flex flex-col items-center justify-center p-8 text-center space-y-8 animate-pulse">
        <div className="w-16 h-16 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold font-heading dark:text-white">Generating Universal Sadhana...</h2>
          <p className="text-slate-500 text-sm">Chanakya is crafting questions for {examConfig.level} in {examConfig.language}.</p>
        </div>
      </div>
    );
  }

  if (view === 'test') {
    return (
      <div className={`space-y-8 pb-20 ${isFocusMode ? 'fixed inset-0 bg-white dark:bg-slate-950 z-[100] overflow-y-auto p-4 md:p-12' : ''}`}>
        <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-slate-50 dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center gap-4">
            <div className={`text-xl font-black ${timer < 300 ? 'text-rose-500 animate-pulse' : 'text-indigo-600 dark:text-indigo-400'}`}>
               <i className="fa-solid fa-clock mr-2"></i> {formatTime(timer)}
            </div>
            <div className="h-6 w-px bg-slate-200 dark:bg-slate-700 hidden md:block"></div>
            <div className="text-left">
              <h3 className="font-bold text-slate-800 dark:text-white text-sm">{examConfig.subject}</h3>
              <p className="text-[10px] text-slate-400 font-bold uppercase">{examConfig.level}</p>
            </div>
          </div>
          <div className="flex gap-3">
            <button 
              onClick={handleDownloadPDF}
              className="bg-indigo-600 text-white px-4 py-2 rounded-xl text-xs font-bold hover:bg-indigo-700 transition-all flex items-center gap-2"
            >
              <i className="fa-solid fa-file-pdf"></i> Download PDF
            </button>
            <button 
              onClick={() => setIsFocusMode(!isFocusMode)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                isFocusMode ? 'bg-amber-500 text-white' : 'bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-300'
              }`}
            >
              <i className={`fa-solid ${isFocusMode ? 'fa-eye' : 'fa-eye-slash'} mr-2`}></i>
              {isFocusMode ? 'Exit Focus' : 'Focus Mode'}
            </button>
            <button onClick={() => setView('selection')} className="bg-rose-100 dark:bg-rose-900/30 text-rose-600 px-4 py-2 rounded-xl text-xs font-bold">End Session</button>
          </div>
        </div>
        
        <div className="max-w-3xl mx-auto space-y-6">
          {questions.length === 0 ? (
            <div className="text-center py-20 text-slate-400">
               <i className="fa-solid fa-face-frown text-4xl mb-4"></i>
               <p>No questions generated. Try broad topics beta.</p>
               <button onClick={() => setView('selection')} className="mt-4 text-indigo-600 font-bold">Go Back</button>
            </div>
          ) : (
            questions.map((q, idx) => (
              <div key={idx} className="bg-white dark:bg-slate-900 p-8 rounded-2xl border border-slate-100 dark:border-slate-800 card-shadow space-y-6 relative group">
                <div className="flex gap-4">
                  <span className="text-slate-400 font-bold text-sm">#{idx + 1}</span>
                  <p className="text-lg text-slate-800 dark:text-slate-200 font-semibold leading-relaxed">{q.text}</p>
                </div>
                <div className="grid gap-3 pl-0 md:pl-8">
                  {q.options.map((opt: string, i: number) => (
                    <button key={i} className="text-left p-4 rounded-xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50 hover:border-indigo-400 hover:bg-white dark:hover:bg-slate-800 transition-all font-medium flex items-center gap-4">
                      <span className="w-8 h-8 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 flex items-center justify-center text-slate-400 text-xs font-bold group-hover:text-indigo-600">{String.fromCharCode(65 + i)}</span> 
                      <span className="text-slate-700 dark:text-slate-300 group-hover:text-slate-900 dark:group-hover:text-white">{opt}</span>
                    </button>
                  ))}
                </div>
                <div className="flex justify-end pt-2 border-t border-slate-50 dark:border-slate-800">
                  <button 
                    onClick={() => trackMistake(q)}
                    className="flex items-center gap-2 text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors py-2 px-4 rounded-lg bg-indigo-50 dark:bg-indigo-900/20"
                  >
                    <i className="fa-solid fa-brain"></i> Explain this Doubt
                  </button>
                </div>
              </div>
            ))
          )}
          {questions.length > 0 && (
            <button className="w-full bg-indigo-600 text-white py-5 rounded-2xl font-bold text-lg shadow-md transition-all tap-active uppercase tracking-widest mt-12">Submit Sadhana</button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-10 pb-20">
      <header className="space-y-2">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white font-heading tracking-tight">Universal Sadhana Hub</h2>
        <p className="text-slate-500 dark:text-slate-400 text-sm font-medium">All Subjects • All Classes • Graduation • Post-Graduation</p>
      </header>

      <section className="bg-white dark:bg-slate-900 p-8 rounded-[32px] border border-slate-200 dark:border-slate-800 card-shadow space-y-8 relative overflow-hidden">
        <div className="absolute top-0 right-0 p-8 opacity-[0.03] pointer-events-none">
           <i className="fa-solid fa-scroll text-[200px] rotate-12"></i>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 relative z-10">
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Academic Level</label>
            <select 
              value={examConfig.level}
              onChange={e => setConfig({...examConfig, level: e.target.value})}
              className="w-full bg-slate-50 dark:bg-slate-800 border-none p-4 rounded-2xl outline-none text-slate-800 dark:text-slate-200 font-bold shadow-inner"
            >
              {levels.map(l => <option key={l} value={l}>{l}</option>)}
            </select>
          </div>
          
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Preferred Language</label>
            <select 
              value={examConfig.language}
              onChange={e => setConfig({...examConfig, language: e.target.value})}
              className="w-full bg-slate-50 dark:bg-slate-800 border-none p-4 rounded-2xl outline-none text-slate-800 dark:text-slate-200 font-bold shadow-inner"
            >
              {languages.map(l => <option key={l} value={l}>{l}</option>)}
            </select>
          </div>

          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Difficulty</label>
            <div className="flex bg-slate-50 dark:bg-slate-800 p-1 rounded-2xl shadow-inner">
              {['Easy', 'Medium', 'Hard'].map(d => (
                <button
                  key={d}
                  onClick={() => setConfig({...examConfig, difficulty: d})}
                  className={`flex-1 py-3 rounded-xl text-[10px] font-black transition-all ${examConfig.difficulty === d ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-400'}`}
                >
                  {d}
                </button>
              ))}
            </div>
          </div>

          <div className="md:col-span-2 space-y-2">
            <label className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Exact Subject</label>
            <input 
              type="text" 
              placeholder="e.g. Applied Mechanics, Sanskrit, Quantum Chemistry..." 
              className="w-full bg-slate-50 dark:bg-slate-800 border-none p-4 rounded-2xl outline-none text-slate-800 dark:text-slate-200 font-bold shadow-inner placeholder:text-slate-400/50"
              value={examConfig.subject}
              onChange={e => setConfig({...examConfig, subject: e.target.value})}
            />
          </div>

          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Specific Unit/Topic</label>
            <input 
              type="text" 
              placeholder="e.g. Thermodynamics, Unit 1..." 
              className="w-full bg-slate-50 dark:bg-slate-800 border-none p-4 rounded-2xl outline-none text-slate-800 dark:text-slate-200 font-bold shadow-inner placeholder:text-slate-400/50"
              value={examConfig.chapters}
              onChange={e => setConfig({...examConfig, chapters: e.target.value})}
            />
          </div>
        </div>

        <button 
          onClick={handleGenerate}
          className="w-full bg-indigo-600 text-white py-6 rounded-3xl font-black text-xl flex items-center justify-center gap-4 shadow-[0_20px_40px_-15px_rgba(79,70,229,0.4)] hover:bg-indigo-700 transition-all tap-active"
        >
          GENERATE PAPER <i className="fa-solid fa-wand-magic-sparkles"></i>
        </button>
      </section>

      {/* Broad Categories Shortcut */}
      <section className="space-y-6">
        <h3 className="text-xl font-bold text-slate-800 dark:text-slate-200 font-heading">Popular Sadhana Paths</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'JEE Mains', icon: 'fa-rocket', color: 'bg-orange-500' },
            { label: 'NEET Bio', icon: 'fa-stethoscope', color: 'bg-emerald-500' },
            { label: 'UGC NET', icon: 'fa-graduation-cap', color: 'bg-blue-500' },
            { label: 'SSC / Bank', icon: 'fa-building-columns', color: 'bg-indigo-500' },
          ].map((path, i) => (
            <button 
                key={i} 
                onClick={() => setConfig({...examConfig, examType: path.label, level: 'Competitive'})}
                className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-100 dark:border-slate-800 flex flex-col items-center gap-3 hover:border-indigo-400 transition-all card-shadow group"
            >
              <div className={`${path.color} w-12 h-12 rounded-2xl flex items-center justify-center text-white shadow-lg group-hover:scale-110 transition-transform`}>
                <i className={`fa-solid ${path.icon}`}></i>
              </div>
              <span className="text-xs font-bold text-slate-700 dark:text-slate-300">{path.label}</span>
            </button>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Exams;
