
import React, { useState } from 'react';
import { generateSpeedNotes, generateStudyMaterial } from '../services/geminiService';

interface RapidProps {
  examLevel: string;
  onAskAI: (t: string) => void;
}

const RapidRevision: React.FC<RapidProps> = ({ examLevel, onAskAI }) => {
  const [topic, setTopic] = useState('');
  const [content, setContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [mode, setMode] = useState<'burst' | 'notes' | 'formulas'>('burst');

  const handleAction = async () => {
    if (!topic.trim() || loading) return;
    setLoading(true);
    setContent(null);
    try {
      let res;
      if (mode === 'burst') {
        res = await generateSpeedNotes(topic, examLevel);
      } else {
        res = await generateStudyMaterial(topic, examLevel, mode === 'notes' ? 'notes' : 'formula_sheet');
      }
      setContent(res);
    } catch (e) {
      setContent("Chanakya's scroll is empty today. Please try again later.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!content) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const contentHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>BharatEdu - ${topic} - ${mode.toUpperCase()}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap');
            body { font-family: 'Inter', sans-serif; padding: 50px; line-height: 1.8; color: #1e293b; max-width: 800px; margin: 0 auto; }
            .header { border-bottom: 2px solid #4f46e5; margin-bottom: 30px; padding-bottom: 10px; }
            .header h1 { margin: 0; color: #4f46e5; font-size: 28px; }
            .meta { font-size: 12px; color: #64748b; margin-top: 5px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
            .content { white-space: pre-wrap; font-size: 15px; color: #334155; }
            .footer { margin-top: 50px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
            h2, h3 { color: #1e1b4b; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${topic}</h1>
            <div class="meta">${mode === 'burst' ? 'Revision Burst' : mode === 'notes' ? 'Master Notes' : 'Formula Sheet'} | ${examLevel}</div>
          </div>
          <div class="content">${content}</div>
          <div class="footer">
            Generated by Chanakya AI via BharatEdu. Support Bharat's education.
          </div>
          <script>window.onload = () => window.print();</script>
        </body>
      </html>
    `;
    printWindow.document.write(contentHtml);
    printWindow.document.close();
  };

  return (
    <div className="space-y-10 pb-20 animate-in slide-in-from-right-10 duration-500">
      <header className="space-y-2">
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white font-heading">Digital Sadhana Vault</h2>
        <p className="text-slate-500 dark:text-slate-400 text-sm">Instantly generate study resources for {examLevel}.</p>
      </header>

      <div className="space-y-4">
        <div className="flex gap-2 p-1 bg-slate-100 dark:bg-slate-900 rounded-2xl w-fit">
          <button 
            onClick={() => setMode('burst')}
            className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'burst' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500'}`}
          >60s Burst</button>
          <button 
            onClick={() => setMode('notes')}
            className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'notes' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500'}`}
          >Study Notes</button>
          <button 
            onClick={() => setMode('formulas')}
            className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'formulas' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500'}`}
          >Formula Sheet</button>
        </div>

        <div className="flex gap-2">
          <input 
            type="text"
            value={topic}
            onChange={e => setTopic(e.target.value)}
            placeholder={`Enter topic (e.g. ${mode === 'formulas' ? 'Integration' : 'Indian Independence'})`}
            className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl px-5 py-4 outline-none focus:ring-2 focus:ring-indigo-500 text-sm font-bold dark:text-white"
          />
          <button 
            onClick={handleAction}
            disabled={loading}
            className="bg-indigo-600 text-white px-8 rounded-2xl font-bold text-sm shadow-xl shadow-indigo-100 dark:shadow-none tap-active disabled:opacity-50"
          >
            {loading ? <i className="fa-solid fa-spinner animate-spin"></i> : <i className="fa-solid fa-wand-magic-sparkles mr-2"></i>}
            {loading ? '' : 'Create'}
          </button>
        </div>
      </div>

      {content && (
        <div className="bg-white dark:bg-slate-900 p-8 rounded-[32px] border border-slate-100 dark:border-slate-800 card-shadow space-y-6 relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-[0.03] pointer-events-none">
            <i className={`fa-solid ${mode === 'burst' ? 'fa-bolt' : 'fa-scroll'} text-[200px] rotate-12`}></i>
          </div>
          <div className="relative z-10">
            <div className="flex justify-between items-center mb-6">
              <span className="text-[10px] font-black text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/40 px-3 py-1.5 rounded-lg uppercase tracking-widest">
                {mode === 'burst' ? 'Revision Burst' : mode === 'notes' ? 'Master Notes' : 'Formula Sheet'}
              </span>
              <div className="flex gap-4">
                <button 
                  onClick={handleDownloadPDF}
                  className="text-[10px] font-black text-slate-400 hover:text-indigo-600 uppercase tracking-widest flex items-center gap-1.5"
                >
                  <i className="fa-solid fa-file-pdf"></i> PDF
                </button>
                <button onClick={() => onAskAI(`Explain this in detail: ${topic}`)} className="text-[10px] font-black text-indigo-600 underline uppercase tracking-widest">Deep Dive</button>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <div className="whitespace-pre-wrap leading-relaxed text-slate-700 dark:text-slate-300 font-medium text-sm md:text-base">
                {content}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Recommended Topics */}
      {!content && !loading && (
        <div className="space-y-4">
          <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest">Recommended for {examLevel}</h3>
          <div className="flex flex-wrap gap-2">
            {['Thermodynamics', 'Organic Chem', 'Modern History', 'Trigonometry', 'Economy Basics'].map(t => (
              <button 
                key={t} 
                onClick={() => setTopic(t)}
                className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 px-4 py-2 rounded-xl text-xs font-bold text-slate-600 dark:text-slate-400 hover:border-indigo-400 transition-all"
              >
                {t}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default RapidRevision;
